[package]
name = "Day1"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.4"
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"] }
regex = "1.10.4"
#scraper = "0.19.0"